Repository manyfold3d/manyfold, pull requests merged in 2024-02, with the labels that each got.

#1811 Add success/error messages and improved redirections for most actions
  app/controllers/collections_controller.rb
  app/controllers/creators_controller.rb
  app/controllers/libraries_controller.rb
  app/controllers/model_files_controller.rb
  app/controllers/models_controller.rb
  app/controllers/problems_controller.rb
  app/controllers/settings_controller.rb
  app/controllers/uploads_controller.rb
  config/locales/en.yml
  content/VanDAM
Labels: feature

#1813 Raise problems for models that are missing image or 3d files
  app/jobs/scan/check_model_integrity_job.rb
  app/models/model.rb
  app/models/model_file.rb
  app/models/problem.rb
  app/views/problems/_model_no_3d_model.html.erb
  app/views/problems/_model_no_image.html.erb
  config/locales/en.yml
  spec/jobs/scan/check_model_integrity_job_spec.rb
Labels: feature

#1817 Hide icons, cards, and filter options for silenced problem types
  app/helpers/models_helper.rb
  app/views/model_files/show.html.erb
  app/views/models/show.html.erb
  app/views/problems/_filters.html.erb
Labels: bug

#1818 Rewrite README to focus on developer documentation
  README.md
Labels: improvement

#1823 Fix database bootstrapping
  .github/workflows/push.yml
  bin/setup
  db/data/20230612080306_remove_destination_exists_problems.rb
  db/data_schema.rb
  db/schema.rb
Labels: bug

#1824 Create CONTRIBUTING guide
  .github/CONTRIBUTING
Labels: improvement

#1826 add link to CLA in CONTRIBUTING
  .github/CONTRIBUTING.md
Labels: documentation

#1843 Set up translation pipeline using translation.io
  .gitignore
  Gemfile
  Gemfile.lock
  README.md
  config/i18n-tasks.yml
  config/initializers/translation.rb
  config/locales/active_admin/en.yml
  config/locales/collections/en.yml
  config/locales/en.yml
  config/locales/libraries/en.yml
  config/locales/links/en.yml
  config/locales/model_files/en.yml
  config/locales/models/en.yml
  config/locales/settings/en.yml
  config/locales/uploads/en.yml
Labels: improvement

#1845 Update Husky test git hooks
  .husky/pre-push
Labels: improvement

#1846 Enable more languages on translation.io
  .gitignore
  config/initializers/translation.rb
Labels: improvement

#1852 Add missing translation keys
  app/controllers/collections_controller.rb
  app/controllers/creators_controller.rb
  app/controllers/libraries_controller.rb
  app/views/application/_links_card.html.erb
  app/views/collections/index.html.erb
  app/views/creators/index.html.erb
  app/views/model_files/_form.html.erb
  app/views/models/_tags_edit.html.erb
  app/views/models/index.html.erb
  app/views/problems/_filters.html.erb
  app/views/settings/_folder_settings.html.erb
  app/views/settings/_folder_settings_description.en.html.erb
  config/locales/collections/en.yml
  config/locales/creators/en.yml
  config/locales/en.yml
  config/locales/libraries/en.yml
  config/locales/model_files/en.yml
  config/locales/models/en.yml
  config/locales/problems/en.yml
  config/locales/settings/en.yml
Labels: improvement, localisation

#1856 Improve translation.io sync config
  config/initializers/translation.rb
  config/locales/devise.en.yml
Labels: localisation

#1876 Automatically pair up supported and unsupported files
  Gemfile
  Gemfile.lock
  app/jobs/model_file_scan_job.rb
  app/jobs/scan/analyse_model_file_job.rb
  app/models/model_file.rb
  spec/jobs/scan/analyse_model_file_job_spec.rb
Labels: feature

#1879 Improved string comparison for file matches
  app/jobs/scan/analyse_model_file_job.rb
  spec/jobs/scan/analyse_model_file_job_spec.rb
Labels: improvement

#1880 Fix scan button
  app/javascript/application.ts
Labels: bug

#1884 Prefer same format when matching supported/unsupported models
  app/jobs/scan/analyse_model_file_job.rb
  app/models/model_file.rb
  spec/jobs/scan/analyse_model_file_job_spec.rb
Labels: feature

#1886 fix user form in Admin UI
  app/admin/users.rb
Labels: improvement

#1889 More accurate part matching when there are multiple options
  app/jobs/scan/analyse_model_file_job.rb
  spec/jobs/scan/analyse_model_file_job_spec.rb
Labels: bug

#1844 Initial German translation
  README.md
  Rakefile
  config/application.rb
  config/i18n-tasks.yml
  config/locales/collections/de.yml
  config/locales/creators/de.yml
  config/locales/de.yml
  config/locales/libraries/de.yml
  config/locales/model_files/de.yml
  config/locales/models/de.yml
  config/locales/problems/de.yml
  config/locales/settings/de.yml
  config/locales/uploads/de.yml
Labels: feature, localisation

#1892 Fix slow model loading
  app/controllers/model_files_controller.rb
Labels: bug

#1908 Update to Node.js 20
  .github/workflows/push.yml
  .node-version
  README.md
  package.json
  yarn.lock
Labels: improvement

#1909 Enable CodeQL security scanning
  .github/workflows/codeql.yml
Labels: security

#1910 Fix or tighten up all lint errors or exemptions
  .rubocop.yml
  .rubocop_todo.yml
  app/admin/delayed_job.rb
  app/controllers/concerns/model_filters.rb
  app/helpers/layouts_helper.rb
  db/migrate/20220106220519_remove_images_table.rb
  db/migrate/20220612220115_add_service_name_to_active_storage_blobs.active_storage.rb
  db/migrate/20220614211256_add_username_to_users.rb
  db/migrate/20230313000001_change_pagination_settings_on_user.rb
  db/migrate/20240228130246_add_missing_unique_indexes.rb
  db/schema.rb
  spec/helpers/application_helper_spec.rb
  spec/helpers/models_helper_spec.rb
  spec/jobs/application_job_spec.rb
  spec/jobs/model_scan_job_spec.rb
  spec/jobs/scan/analyse_model_file_job_spec.rb
  spec/jobs/scan/check_model_integrity_job_spec.rb
  spec/jobs/scan/detect_filesystem_changes_job_spec.rb
  spec/lib/supported_mime_types_spec.rb
  spec/models/concerns/path_parser_spec.rb
  spec/models/library_spec.rb
  spec/models/model_file_spec.rb
  spec/models/model_spec.rb
  spec/models/problem_spec.rb
  spec/requests/collections_request_spec.rb
  spec/requests/creators_request_spec.rb
  spec/requests/home_spec.rb
  spec/requests/libraries_request_spec.rb
  spec/requests/model_files_request_spec.rb
  spec/requests/models_request_spec.rb
Labels: improvement
