Repository manyfold3d/manyfold, pull requests merged in 2024-08, with the labels that each got.

#2471 Allow users to follow models, creators, and collections
  Gemfile
  Gemfile.lock
  app/components/follow_button.html.erb
  app/components/follow_button.rb
  app/controllers/follows_controller.rb
  app/models/collection.rb
  app/models/concerns/followable.rb
  app/models/concerns/follower.rb
  app/models/creator.rb
  app/models/model.rb
  app/models/user.rb
  app/policies/federails/following_policy.rb
  app/views/models/index.html.erb
  app/views/models/show.html.erb
  config/i18n-tasks.yml
  config/initializers/federails.rb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20240731165646_change_actor_entity_rel_to_polymorphic.federails.rb
  db/schema.rb
  spec/components/follow_button_spec.rb
  spec/models/collection_spec.rb
  spec/models/concerns/follower_shared.rb
  spec/models/creator_spec.rb
  spec/models/model_spec.rb
  spec/models/user_spec.rb
  spec/requests/follows_spec.rb
  spec/support/view_components.rb
Labels: feature

#2483 Auto-create more Federails actors
  app/models/concerns/federails_common.rb
  app/models/concerns/followable.rb
  app/models/concerns/follower.rb
  db/data/20240731124820_create_federails_actors.rb
  db/data/20240802094448_create_more_federails_actors.rb
  db/data_schema.rb
Labels: improvement

#2484 Fix URL option settings
  config/application.rb
  config/initializers/federails.rb
Labels: improvement

#2485 Add a stable env var for the rails app port
  bin/dev
  bin/docker-entrypoint.sh
  config/application.rb
Labels: improvement

#2486 Show all activities in feed
  app/controllers/home_controller.rb
  app/helpers/application_helper.rb
  app/views/activities/_create_actor.html.erb
Labels: improvement

#2487 Move Create activity post into shared Followable concern
  app/models/concerns/followable.rb
  app/models/model.rb
Labels: improvement

#2489 Make sure default activity user is an admin
  app/models/concerns/followable.rb
Labels: improvement

#2490 Backfill last 20 creation activities on migration
  db/data/20240805111500_backfill_activities.rb
  db/data_schema.rb
Labels: improvement

#2492 Refactor local timeline generation
  app/controllers/home_controller.rb
  app/lib/timeline.rb
Labels: improvement

#2493 Fix frozen string problem in locale fallback
  config/initializers/i18n.rb
Labels: bug

#2494 Ignore hidden files and folders during scan and upload
  app/jobs/process_uploaded_file_job.rb
  spec/jobs/process_uploaded_file_job_spec.rb
  spec/jobs/scan/detect_filesystem_changes_job_spec.rb
Labels: bug

#2495 Further improvements to tag performance
  app/controllers/collections_controller.rb
  app/controllers/concerns/filterable.rb
  app/controllers/concerns/tag_listable.rb
  app/controllers/creators_controller.rb
  app/controllers/home_controller.rb
  app/controllers/models_controller.rb
  app/views/application/_filters_card.html.erb
  app/views/application/_tag.html.erb
  app/views/application/_tag_list.html.erb
  app/views/application/_tags_card.html.erb
  app/views/collections/index.html.erb
  app/views/creators/index.html.erb
  app/views/models/bulk_edit.html.erb
  app/views/models/index.html.erb
  config/locales/collections/de.yml
  config/locales/collections/en.yml
  config/locales/collections/fr.yml
  config/locales/collections/pl.yml
  config/locales/creators/de.yml
  config/locales/creators/en.yml
  config/locales/creators/fr.yml
  config/locales/creators/pl.yml
  config/locales/de.yml
  config/locales/en.yml
  config/locales/fr.yml
  config/locales/models/de.yml
  config/locales/models/en.yml
  config/locales/models/fr.yml
  config/locales/models/pl.yml
  config/locales/pl.yml
Labels: bug

#2500 Fix LIKE query on PostgreSQL
  app/controllers/concerns/tag_listable.rb
Labels: bug

#2501 Fix tag lists in bulk editing
  app/components/follow_button.html.erb
  app/components/follow_button_component.rb
  app/components/tag_component.rb
  app/controllers/models_controller.rb
  app/views/application/_tag_list.html.erb
  app/views/models/bulk_edit.html.erb
  app/views/models/index.html.erb
  app/views/models/show.html.erb
  spec/components/follow_button_component_spec.rb
Labels: bug

#2503 Reorder data migration to avoid error
  db/data/20240731165647_create_federails_actors.rb
Labels: bug

#2507 Remove Flipper for feature switching
  .gitignore
  Gemfile
  Gemfile.lock
  app/components/follow_button_component.rb
  app/controllers/users/sessions_controller.rb
  app/models/site_settings.rb
  app/policies/application_policy.rb
  app/policies/federails/following_policy.rb
  app/policies/library_policy.rb
  app/policies/model_policy.rb
  app/policies/upload_policy.rb
  app/policies/user_policy.rb
  app/policies/users/passwords_policy.rb
  app/policies/users/registrations_policy.rb
  app/policies/users/sessions_policy.rb
  app/views/activity/index.html.erb
  app/views/application/_navbar.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/home/index.html.erb
  app/views/settings/_multiuser_settings.html.erb
  app/views/settings/show.html.erb
  config/application.rb
  config/initializers/active_admin.rb
  config/initializers/federails.rb
  config/initializers/flipper.rb
  config/routes.rb
  spec/components/follow_button_component_spec.rb
  spec/requests/admin/collections_spec.rb
  spec/requests/admin/creators_spec.rb
  spec/requests/admin/dashboard_spec.rb
  spec/requests/admin/link_spec.rb
  spec/requests/admin/log_spec.rb
  spec/requests/admin/model_files_spec.rb
  spec/requests/admin/models_spec.rb
  spec/requests/admin/problem_spec.rb
  spec/requests/admin/tags_spec.rb
  spec/requests/users/registrations_spec.rb
  spec/support/features.rb
  spec/support/multiuser.rb
Labels: improvement

#2508 Get Webfinger working for users, models, collections, and creators
  Gemfile.lock
  app/models/concerns/followable.rb
  app/models/concerns/follower.rb
  config/application.rb
  config/initializers/federails.rb
  config/routes.rb
  spec/requests/webfinger_spec.rb
Labels: improvement

#2509 Post and display update activities
  app/lib/timeline.rb
  app/models/concerns/followable.rb
  app/views/activities/_update_actor.html.erb
Labels: feature

#2512 Handle user signups in local feed
  app/helpers/application_helper.rb
  app/views/activities/_create_actor.html.erb
Labels: improvement

#2511 Set proper types for each actor
  Gemfile.lock
  app/models/collection.rb
  app/models/concerns/followable.rb
  app/models/concerns/follower.rb
  app/models/creator.rb
  app/models/model.rb
  app/models/user.rb
Labels: improvement

#2529 Remove temporarily-created models if ProcessUploadedFileJob fails
  app/jobs/process_uploaded_file_job.rb
  spec/jobs/process_uploaded_file_job_spec.rb
Labels: bug

#2533 Don't link to users from activity feed
  app/views/activities/_create_actor.html.erb
  app/views/activities/_update_actor.html.erb
Labels: bug

#2535 Hide user updates and fix local links in activity feed
  app/views/activities/_create_actor.html.erb
  app/views/activities/_update_actor.html.erb
Labels: bug

#2537 Fix entity -> actor relationship
  Gemfile.lock
Labels: bug

#2538 Don't repeat activities within 5 minutes
  Gemfile.lock
  app/models/concerns/followable.rb
  spec/models/concerns/followable_shared.rb
Labels: improvement

#2539 German translation updates by @mallo321123
  config/locales/collections/de.yml
  config/locales/creators/de.yml
  config/locales/de.yml
  config/locales/devise/de.yml
  config/locales/libraries/de.yml
  config/locales/model_files/de.yml
  config/locales/models/de.yml
  config/locales/problems/de.yml
  config/locales/settings/de.yml
Labels: improvement, localisation

#2540 Polish translation updates by @XioR112
  config/locales/devise/pl.yml
  config/locales/libraries/pl.yml
  config/locales/pl.yml
Labels: improvement, localisation

#2541 Make create/update activity feed items translatable
  app/views/activities/_create_actor.html.erb
  app/views/activities/_update_actor.html.erb
  config/locales/en.yml
Labels: improvement, localisation

#2542 i18n renormalization
  config/locales/en.yml
Labels: improvement

#2551 Fix error on untagged model listing
  app/views/application/_tag_list.html.erb
Labels: bug

#2552 Fix some raw html appearing in text when translations are missing
  app/helpers/uploads_helper.rb
  app/views/collections/_form.html.erb
  app/views/creators/_form.html.erb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/libraries/_form.html.erb
  app/views/model_files/bulk_edit.html.erb
  app/views/models/bulk_edit.html.erb
  app/views/models/new.html.erb
Labels: bug

#2553 Ignore Synology-generated files
  app/jobs/model_scan_job.rb
  app/jobs/process_uploaded_file_job.rb
  app/models/library.rb
  app/models/site_settings.rb
  spec/jobs/process_uploaded_file_job_spec.rb
  spec/models/site_settings_spec.rb
Labels: feature

#2555 Handle non-existent actor in following check
  app/models/concerns/follower.rb
Labels: bug

#2558 Exclude followable objects from nodeinfo stats
  app/models/collection.rb
  app/models/creator.rb
  app/models/model.rb
Labels: bug

#2559 Don't set standard ports in URL options
  config/application.rb
Labels: bug

#2561 Exclude healthcheck endpoint from forced SSL
  config/environments/production.rb
Labels: bug

#2562 Include scheme in federails site host config
  config/initializers/federails.rb
Labels: bug

#2560 Remove foreign key before dropping index
  db/migrate/20240727113215_create_federails_actors.federails.rb
Labels: bug

#2564 Create actor for default user if missing on create activities
  app/models/concerns/followable.rb
Labels: bug

#2565 Allow federation on single-user instances
  app/components/follow_button_component.rb
  app/policies/federails/following_policy.rb
  config/routes.rb
Labels: feature

#2584 Upgrade to latest alpine release
  docker/base.dockerfile
Labels: improvement

#2586 Update to Ruby 3.3.4
  .ruby-version
  docker/base.dockerfile
Labels: improvement

#2588 Add rich per-user and per-object permission controls
  Gemfile
  Gemfile.lock
  app/models/collection.rb
  app/models/concerns/default_view_permissions.rb
  app/models/concerns/followable.rb
  app/models/creator.rb
  app/models/model.rb
  app/models/role.rb
  app/models/site_settings.rb
  app/models/user.rb
  app/policies/application_policy.rb
  app/policies/collection_policy.rb
  app/policies/creator_policy.rb
  app/policies/model_policy.rb
  config/initializers/caber.rb
  db/data/20240830121749_add_default_access_controls.rb
  db/data_schema.rb
  db/migrate/20240827155630_create_caber_relations.rb
  db/schema.rb
  spec/factories/role.rb
  spec/models/collection_spec.rb
  spec/models/concerns/caber_object_shared.rb
  spec/models/concerns/caber_subject_shared.rb
  spec/models/creator_spec.rb
  spec/models/model_spec.rb
  spec/models/role_spec.rb
  spec/models/user_spec.rb
  spec/policies/application_policy_spec.rb
  spec/support/pundit.rb
Labels: feature

#2592 Set owner permissions for uploaded files
  app/controllers/models_controller.rb
  app/jobs/process_uploaded_file_job.rb
  spec/jobs/process_uploaded_file_job_spec.rb
Labels: feature

#2593 Rename default roles for greater clarity alongside ReBAC permissions
  app/jobs/process_uploaded_file_job.rb
  app/models/concerns/default_view_permissions.rb
  app/models/concerns/followable.rb
  app/models/role.rb
  app/models/user.rb
  app/policies/application_policy.rb
  app/policies/model_file_policy.rb
  app/policies/model_policy.rb
  config/initializers/caber.rb
  db/data/20240830151650_rename_default_roles.rb
  db/data_schema.rb
  spec/factories/user.rb
  spec/helpers/problems_helper_spec.rb
  spec/jobs/process_uploaded_file_job_spec.rb
  spec/models/role_spec.rb
  spec/models/user_spec.rb
  spec/policies/application_policy_spec.rb
  spec/requests/activity_spec.rb
  spec/requests/admin/collections_spec.rb
  spec/requests/admin/creators_spec.rb
  spec/requests/admin/dashboard_spec.rb
  spec/requests/admin/link_spec.rb
  spec/requests/admin/log_spec.rb
  spec/requests/admin/model_files_spec.rb
  spec/requests/admin/models_spec.rb
  spec/requests/admin/problem_spec.rb
  spec/requests/admin/tags_spec.rb
  spec/requests/collections_spec.rb
  spec/requests/creators_spec.rb
  spec/requests/home_spec.rb
  spec/requests/libraries_spec.rb
  spec/requests/model_files_spec.rb
  spec/requests/models_spec.rb
  spec/requests/problems_spec.rb
  spec/requests/settings_spec.rb
  spec/requests/uploads_spec.rb
  spec/requests/users/sessions_spec.rb
  spec/support/sign_in_role.rb
Labels: improvement
