Repository manyfold3d/manyfold, pull requests merged in 2024-04, with the labels that each got.

#1993 Refactor default severity fallback to be more DRY
  app/controllers/problems_controller.rb
  app/helpers/problems_helper.rb
  app/models/user.rb
  app/views/problems/_filters.html.erb
  app/views/settings/_problem_settings.html.erb
Labels: improvement

#1981 Check for non-manifold mesh errors
  Gemfile
  Gemfile.lock
  app/jobs/scan/analyse_model_file_job.rb
  app/jobs/scan/geometric_analysis_job.rb
  app/lib/mesh_analysis.rb
  app/models/model_file.rb
  app/models/problem.rb
  app/views/model_files/_problem.html.erb
  app/views/problems/model_file/_inside_out.html.erb
  app/views/problems/model_file/_non_manifold.html.erb
  config/initializers/delayed_job_extensions.rb
  config/initializers/mittsu.rb
  config/locales/problems/en.yml
  spec/jobs/scan/analyse_model_file_job_spec.rb
  spec/jobs/scan/geometric_analysis_job_spec.rb
  spec/lib/mesh_analysis_spec.rb
Labels: feature

#2001 Don't treat files without digests as duplicates
  app/models/model_file.rb
  spec/models/model_file_spec.rb
Labels: bug

#2003 Add a button to rescan an individual model
  app/controllers/models_controller.rb
  app/policies/model_policy.rb
  app/views/models/show.html.erb
  config/locales/models/en.yml
  config/locales/problems/en.yml
  config/routes.rb
  spec/requests/models_spec.rb
Labels: feature

#2004 Translation updates for PL and FR
  config/locales/de.yml
  config/locales/devise/de.yml
  config/locales/devise/fr.yml
  config/locales/devise/pl.yml
  config/locales/models/de.yml
  config/locales/models/fr.yml
  config/locales/models/pl.yml
  config/locales/problems/de.yml
  config/locales/problems/fr.yml
  config/locales/problems/pl.yml
  config/locales/settings/fr.yml
  config/locales/settings/pl.yml
Labels: improvement, localisation

#2008 Reorganise analysis jobs into their own namespace
  app/jobs/analysis/analyse_model_file_job.rb
  app/jobs/analysis/geometric_analysis_job.rb
  app/jobs/model_file_scan_job.rb
  app/jobs/scan/check_model_job.rb
  app/models/model_file.rb
  spec/jobs/analysis/analyse_model_file_job_spec.rb
  spec/jobs/analysis/geometric_analysis_job_spec.rb
  spec/jobs/model_file_scan_job_spec.rb
  spec/jobs/scan/check_model_job_spec.rb
  spec/models/model_file_spec.rb
Labels: improvement

#2009 Temporarily disable inside-out check while we debug
  app/jobs/analysis/geometric_analysis_job.rb
  spec/jobs/analysis/geometric_analysis_job_spec.rb
Labels: improvement

#2011 Better failure handling for background scan jobs
  app/jobs/analysis/analyse_model_file_job.rb
  app/jobs/analysis/geometric_analysis_job.rb
  app/jobs/model_file_scan_job.rb
  app/jobs/model_scan_job.rb
  app/jobs/scan/check_model_integrity_job.rb
  app/jobs/scan/check_model_job.rb
  spec/jobs/analysis/analyse_model_file_job_spec.rb
  spec/jobs/analysis/geometric_analysis_job_spec.rb
  spec/jobs/model_file_scan_job_spec.rb
  spec/jobs/model_scan_job_spec.rb
  spec/jobs/scan/check_model_integrity_job_spec.rb
  spec/jobs/scan/check_model_job_spec.rb
Labels: bug

#2013 Don't show nested model list in wrong places
  app/views/models/_problem.html.erb
Labels: bug

#2012 Fix occasionally invalid default admin password
  app/controllers/users/sessions_controller.rb
Labels: bug

#1997 Allow for modular setting of database connection string
  bin/docker-entrypoint.sh
  docker-compose.example.yml
Labels: feature

#2019 Use default problem severities if setting isn't available
  app/models/problem.rb
  spec/models/problem_spec.rb
Labels: bug

#2023 Fix incorrect condition for manifold checks
  app/jobs/analysis/geometric_analysis_job.rb
Labels: bug

#2026 Optimise STL loader
  Gemfile.lock
Labels: improvement

#2027 Add "remember me" option at login
  app/models/user.rb
  app/views/devise/sessions/new.html.erb
  db/migrate/20220614210023_devise_create_users.rb
  db/migrate/20240410221112_add_rememberable_to_users.rb
  db/schema.rb
Labels: feature

#2030 Add ability to reset lost passwords
  Gemfile
  Gemfile.lock
  app/controllers/users/passwords_controller.rb
  app/mailers/application_mailer.rb
  app/models/site_settings.rb
  app/models/user.rb
  app/policies/users/passwords_policy.rb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/shared/_links.html.erb
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/initializers/devise.rb
  config/routes.rb
  db/migrate/20220614210023_devise_create_users.rb
  db/migrate/20240410222922_add_reset_password_sent_at_to_users.rb
  db/schema.rb
  spec/requests/users/passwords_spec.rb
Labels: feature

#2033 Show images in a carousel above models
  app/assets/stylesheets/models.scss
  app/controllers/models_controller.rb
  app/views/models/_image_carousel.html.erb
  app/views/models/show.html.erb
  config/locales/models/de.yml
  config/locales/models/en.yml
  config/locales/models/fr.yml
  config/locales/models/pl.yml
Labels: feature

#2035 Only list 3d files in bulk editor
  app/controllers/model_files_controller.rb
  app/views/model_files/bulk_edit.html.erb
Labels: feature

#2044 Fixes to 3MF conversion
  Gemfile.lock
  app/controllers/model_files_controller.rb
  app/jobs/analysis/analyse_model_file_job.rb
  app/jobs/analysis/file_conversion_job.rb
  app/jobs/analysis/geometric_analysis_job.rb
  app/jobs/model_file_scan_job.rb
  app/jobs/model_scan_job.rb
  app/jobs/scan/check_model_integrity_job.rb
  app/jobs/scan/check_model_job.rb
Labels: improvement

#2051 Change to Sidekiq to run background jobs
  Gemfile
  Gemfile.lock
  Procfile
  Procfile.dev
  README.md
  app/admin/dashboard.rb
  app/admin/delayed_job.rb
  app/controllers/application_controller.rb
  app/jobs/model_file_scan_job.rb
  app/jobs/model_scan_job.rb
  app/jobs/scan/detect_filesystem_changes_job.rb
  app/policies/delayed/backend/active_record/job_policy.rb
  app/views/application/_navbar.html.erb
  app/views/settings/show.html.erb
  bin/delayed_job
  config/environments/development.rb
  config/environments/production.rb
  config/initializers/delayed_job_extensions.rb
  config/locales/de.yml
  config/locales/en.yml
  config/locales/fr.yml
  config/locales/pl.yml
  config/locales/settings/de.yml
  config/locales/settings/en.yml
  config/locales/settings/fr.yml
  config/locales/settings/pl.yml
  config/routes.rb
  config/sidekiq.yml
  db/migrate/20240418112821_drop_delayed_jobs.rb
  db/schema.rb
  spec/jobs/analysis/analyse_model_file_job_spec.rb
  spec/jobs/analysis/file_conversion_job_spec.rb
  spec/jobs/model_file_scan_job_spec.rb
  spec/jobs/model_scan_job_spec.rb
  spec/jobs/scan/check_all_job_spec.rb
  spec/jobs/scan/check_model_job_spec.rb
  spec/jobs/scan/detect_filesystem_changes_job_spec.rb
  spec/models/model_file_spec.rb
  spec/requests/admin/delayed_job_spec.rb
  spec/support/sidekiq.rb
Labels: improvement

#2054 Check library paths are correct on case-preserving filesystems
  app/models/library.rb
  spec/models/library_spec.rb
Labels: bug

#2056 Add a friendly activity log showing background tasks and results
  Gemfile
  Gemfile.lock
  app/controllers/activity_controller.rb
  app/helpers/activity_helper.rb
  app/jobs/application_job.rb
  app/jobs/scan/detect_filesystem_changes_job.rb
  app/policies/activity_policy.rb
  app/views/activity/index.html.erb
  app/views/application/_navbar.html.erb
  app/views/settings/show.html.erb
  config/initializers/activejob_status.rb
  config/locales/de.yml
  config/locales/en.yml
  config/locales/fr.yml
  config/locales/model_files/en.yml
  config/locales/pl.yml
  config/locales/settings/de.yml
  config/locales/settings/en.yml
  config/locales/settings/fr.yml
  config/locales/settings/pl.yml
  config/routes.rb
  content/VanDAM
  spec/requests/activity_spec.rb
Labels: feature

#2058 Paginate activities with Kaminari
  app/controllers/activity_controller.rb
  app/views/activity/index.html.erb
Labels: improvement

#2059 ignore errors thrown by settings cache clear
  app/jobs/application_job.rb
Labels: bug

#2063 Pluralize footer model names correctly
  app/views/application/_footer.html.erb
Labels: bug

#2067 Enable brakeman security analysis
  .codeclimate.yml
Labels: improvement, security

#2068 Add brakeman gem for local analysis
  Gemfile
  Gemfile.lock
Labels: improvement, security

#2070 Accessibility improvements from manual aXe testing
  app/components/model_component.html.erb
  app/helpers/application_helper.rb
  app/javascript/src/preview.ts
  app/views/application/_footer.html.erb
  app/views/application/_navbar.html.erb
  app/views/collections/_collection.html.erb
  app/views/creators/_creator.html.erb
  app/views/layouts/application.html.erb
  app/views/models/_file.html.erb
  app/views/models/_form.html.erb
  app/views/models/show.html.erb
  spec/helpers/application_helper_spec.rb
Labels: improvement, accessibility

#2074 Fix translation of pluralized model names
  app/helpers/problems_helper.rb
  app/views/application/_filters_card.html.erb
  app/views/application/_footer.html.erb
  app/views/application/_links_card.html.erb
  app/views/application/_navbar.html.erb
  app/views/application/_tag_list.html.erb
  app/views/collections/_collection.html.erb
  app/views/collections/index.html.erb
  app/views/creators/_creator.html.erb
  app/views/creators/index.html.erb
  app/views/model_files/bulk_edit.html.erb
  app/views/models/bulk_edit.html.erb
  app/views/models/index.html.erb
  app/views/models/show.html.erb
  app/views/problems/index.html.erb
  config/locales/de.yml
  config/locales/en.yml
  config/locales/fr.yml
  config/locales/pl.yml
Labels: bug, localisation

#2077 Explicitly setting for interface language
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/settings_controller.rb
  app/views/settings/_general_settings.html.erb
  app/views/settings/show.html.erb
  config/locales/settings/de.yml
  config/locales/settings/en.yml
  config/locales/settings/fr.yml
  config/locales/settings/pl.yml
  db/migrate/20240423102250_add_interface_language_to_users.rb
  db/schema.rb
Labels: feature, accessibility

#2078 More translation updates
  .github/workflows/push.yml
  config/locales/de.yml
  config/locales/fr.yml
  config/locales/model_files/fr.yml
  config/locales/pl.yml
Labels: improvement, localisation

#2079 More translation tidying up
  app/jobs/analysis/analyse_model_file_job.rb
  app/jobs/analysis/file_conversion_job.rb
  app/jobs/analysis/geometric_analysis_job.rb
  app/jobs/scan/check_all_job.rb
  app/jobs/scan/detect_filesystem_changes_job.rb
  config/i18n-tasks.yml
  config/locales/active_admin/en.yml
  config/locales/de.yml
  config/locales/devise.en.yml
  config/locales/devise/de.yml
  config/locales/devise/en.yml
  config/locales/devise/fr.yml
  config/locales/devise/pl.yml
  config/locales/en.yml
  config/locales/fr.yml
  config/locales/pl.yml
Labels: improvement, localisation

#2080 Fix right-click behaviour
  app/assets/stylesheets/application.bootstrap.scss
Labels: bug

#2081 Add plural forms for models in english
  config/locales/en.yml
Labels: bug, localisation

#2082 Change unassigned creator/collection into panels
  app/views/collections/_unassigned.html.erb
  app/views/collections/index.html.erb
  app/views/creators/_unassigned.html.erb
  app/views/creators/index.html.erb
  config/locales/collections/de.yml
  config/locales/collections/en.yml
  config/locales/collections/fr.yml
  config/locales/collections/pl.yml
  config/locales/creators/de.yml
  config/locales/creators/en.yml
  config/locales/creators/fr.yml
  config/locales/creators/pl.yml
Labels: improvement

#2085 Reduce N+1 database queries
  Gemfile
  Gemfile.lock
  app/controllers/collections_controller.rb
  app/controllers/creators_controller.rb
  app/controllers/home_controller.rb
  app/controllers/model_files_controller.rb
  app/controllers/models_controller.rb
  app/controllers/problems_controller.rb
  app/views/model_files/_breadcrumb.html.erb
  app/views/models/_file.html.erb
  app/views/models/_form.html.erb
  app/views/models/_image_carousel.html.erb
  app/views/models/_problem.html.erb
  app/views/models/show.html.erb
  config/environments/development.rb
  config/environments/test.rb
  spec/requests/models_spec.rb
Labels: improvement, performance

#2086 Fix error with unpaginated creators and collections
  app/views/collections/index.html.erb
  app/views/creators/index.html.erb
Labels: bug

#2087 Optimise model list page by making permission lookup more efficient
  Gemfile
  Gemfile.lock
  Procfile.dev
  app/components/model_component.html.erb
  app/components/model_component.rb
  app/controllers/models_controller.rb
Labels: improvement, performance

#2088 Fix missing buttons on model list
  app/views/models/index.html.erb
Labels: bug

#2120 A11y fixes for problem icons, including shape differentiation
  app/helpers/application_helper.rb
  app/helpers/models_helper.rb
  app/helpers/problems_helper.rb
  app/views/application/_navbar.html.erb
  app/views/layouts/application.html.erb
  app/views/models/_file.html.erb
  spec/helpers/application_helper_spec.rb
Labels: improvement, accessibility

#2122 Move breadcrumbs into a top-level nav for better accessibility
  app/views/layouts/application.html.erb
  app/views/model_files/_breadcrumb.html.erb
Labels: improvement, accessibility

#2123 Improve bulk editor accessibility
  app/views/model_files/bulk_edit.html.erb
  app/views/models/bulk_edit.html.erb
  config/locales/model_files/en.yml
  config/locales/models/en.yml
Labels: improvement, accessibility

#2124 Polish translation updates
  config/locales/collections/pl.yml
  config/locales/creators/pl.yml
  config/locales/pl.yml
Labels: improvement

#2125 Add a skip link to get to main content
  app/assets/stylesheets/application.bootstrap.scss
  app/assets/stylesheets/layout.scss
  app/views/application/_navbar.html.erb
  app/views/home/index.html.erb
  app/views/layouts/application.html.erb
  config/locales/en.yml
Labels: improvement, accessibility

#2129 Add skip links for large content blocks (models, creators, collections, tags)
  app/assets/stylesheets/layout.scss
  app/helpers/application_helper.rb
  app/views/application/_footer.html.erb
  app/views/collections/index.html.erb
  app/views/creators/index.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/card_list_page.html.erb
  app/views/models/index.html.erb
  config/locales/collections/en.yml
  config/locales/creators/en.yml
  config/locales/en.yml
  config/locales/models/en.yml
Labels: improvement, accessibility

#2130 Show constraints alongside password input boxes
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/first_use.html.erb
  app/views/devise/registrations/new.html.erb
  config/locales/devise/en.yml
Labels: improvement, accessibility

#2131 Add ARIA labels for pagination links
  config/locales/en.yml
Labels: bug, accessibility
