Repository manyfold3d/manyfold, pull requests merged in 2025-02, with the labels that each got.

#3538 Show remote models and collections in lists
  app/assets/stylesheets/src/models.scss
  app/components/model_component.html.erb
  app/deserializers/activity_pub/model_deserializer.rb
  app/models/collection.rb
  app/models/creator.rb
  app/views/collections/_collection.html.erb
  app/views/collections/_form.html.erb
  app/views/creators/_creator.html.erb
  app/views/creators/show.html.erb
  app/views/models/_bulk_fields.html.erb
  app/views/models/_form.html.erb
  config/locales/collections/en.yml
  config/locales/creators/en.yml
  config/locales/en.yml
  spec/deserializers/activity_pub/model_deserializer_spec.rb
Labels: feature, federation

#3541 Don't show permission options for remote objects
  app/views/application/_caber_relations_form.html.erb
Labels: improvement

#3542 Added a simple "following" page
  app/controllers/follows_controller.rb
  app/views/follows/_actor_table.html.erb
  app/views/follows/_search_form.html.erb
  app/views/follows/index.html.erb
  app/views/follows/new.html.erb
  config/locales/de.yml
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/nl.yml
  config/locales/pl.yml
Labels: feature, federation

#3547 Link names to profiles on actor table
  app/views/follows/_actor_table.html.erb
Labels: improvement

#3543 Create remote objects only when follow is accepted
  Gemfile
  Gemfile.lock
  app/controllers/follows_controller.rb
  app/models/concerns/followable.rb
  app/models/concerns/follower.rb
  spec/requests/webfinger_spec.rb
Labels: improvement, federation

#3557 Set a valid user-agent string
  config/initializers/user_agent.rb
Labels: improvement

#3558 update federails
  Gemfile.lock
  spec/models/concerns/follower_shared.rb
  spec/requests/webfinger_spec.rb
Labels: dependencies

#3559 Automatically update and create remote federated objects
  app/deserializers/activity_pub/application_deserializer.rb
  app/deserializers/activity_pub/collection_deserializer.rb
  app/deserializers/activity_pub/creator_deserializer.rb
  app/deserializers/activity_pub/model_deserializer.rb
  app/models/concerns/followable.rb
  app/models/concerns/follower.rb
  app/services/activity_pub/actor_activity_handler.rb
  config/initializers/federails.rb
  spec/deserializers/activity_pub/collection_deserializer_spec.rb
  spec/deserializers/activity_pub/creator_deserializer_spec.rb
  spec/deserializers/activity_pub/model_deserializer_spec.rb
Labels: feature, federation

#3564 Show server for remote objects in activity feed
  app/components/model_component.html.erb
  app/helpers/application_helper.rb
  app/views/activities/_create_actor.html.erb
  app/views/activities/_update_actor.html.erb
  app/views/collections/_collection.html.erb
  app/views/creators/_creator.html.erb
  config/locales/collections/en.yml
  config/locales/creators/en.yml
  config/locales/en.yml
Labels: feature, federation

#3565 Don't check remote models for problems
  app/jobs/model_scan_job.rb
  app/jobs/scan/check_model_integrity_job.rb
Labels: bug

#3566 Overwrite links in remote object deserialization
  app/deserializers/activity_pub/collection_deserializer.rb
  app/deserializers/activity_pub/creator_deserializer.rb
  app/deserializers/activity_pub/model_deserializer.rb
Labels: bug

#3567 Add note that remote previews aren't available yet
  app/assets/stylesheets/src/models.scss
  app/components/model_component.html.erb
  config/locales/en.yml
Labels: improvement

#3577 Fix bug when creating followed entities
  app/models/concerns/follower.rb
Labels: bug, federation

#3583 Add the ability to select from bootwatch themes
  Rakefile
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/entrypoints/themes/cerulean.scss
  app/assets/stylesheets/entrypoints/themes/cosmo.scss
  app/assets/stylesheets/entrypoints/themes/cyborg.scss
  app/assets/stylesheets/entrypoints/themes/darkly.scss
  app/assets/stylesheets/entrypoints/themes/default.scss
  app/assets/stylesheets/entrypoints/themes/flatly.scss
  app/assets/stylesheets/entrypoints/themes/journal.scss
  app/assets/stylesheets/entrypoints/themes/litera.scss
  app/assets/stylesheets/entrypoints/themes/lumen.scss
  app/assets/stylesheets/entrypoints/themes/lux.scss
  app/assets/stylesheets/entrypoints/themes/materia.scss
  app/assets/stylesheets/entrypoints/themes/minty.scss
  app/assets/stylesheets/entrypoints/themes/morph.scss
  app/assets/stylesheets/entrypoints/themes/pulse.scss
  app/assets/stylesheets/entrypoints/themes/quartz.scss
  app/assets/stylesheets/entrypoints/themes/sandstone.scss
  app/assets/stylesheets/entrypoints/themes/simplex.scss
  app/assets/stylesheets/entrypoints/themes/sketchy.scss
  app/assets/stylesheets/entrypoints/themes/slate.scss
  app/assets/stylesheets/entrypoints/themes/solar.scss
  app/assets/stylesheets/entrypoints/themes/spacelab.scss
  app/assets/stylesheets/entrypoints/themes/superhero.scss
  app/assets/stylesheets/entrypoints/themes/united.scss
  app/assets/stylesheets/entrypoints/themes/vapor.scss
  app/assets/stylesheets/entrypoints/themes/yeti.scss
  app/assets/stylesheets/entrypoints/themes/zephyr.scss
  app/controllers/application_controller.rb
  app/views/application/_navbar.html.erb
  app/views/home/index.html.erb
  app/views/layouts/application.html.erb
  package.json
  spec/support/maintain_test_assets.rb
  yarn.lock
Labels: feature

#3584 Fix various 3MF display issues, including production extension
  app/javascript/offscreen_renderer.ts
  yarn.lock
Labels: bug

#3586 Add theme chooser in site settings area
  app/controllers/settings_controller.rb
  app/models/site_settings.rb
  app/policies/settings_policy.rb
  app/views/layouts/application.html.erb
  app/views/layouts/settings.html.erb
  app/views/settings/appearance.html.erb
  config/locales/en.yml
  config/locales/settings/en.yml
  config/routes.rb
Labels: feature

#3587 Force puma to bind to IPv6 addresses
  config/puma.rb
Labels: bug

#3588 Fix menu clipping when previews are missing
  app/assets/stylesheets/src/models.scss
Labels: bug

#3606 move to rpg-awesome-continued
  app/assets/stylesheets/application.scss
  package.json
  yarn.lock
Labels: dependencies

#3608 Force binding to IPv6 address
  Procfile
  Procfile.dev
Labels: bug

#3609 Use the Fediverse asterism symbol instead of globe
  app/components/model_component.html.erb
  app/helpers/application_helper.rb
  app/views/collections/edit.html.erb
  app/views/creators/_creator.html.erb
  app/views/models/show.html.erb
  config/locales/collections/en.yml
  config/locales/creators/en.yml
  config/locales/en.yml
  config/locales/models/en.yml
Labels: improvement, federation

#3611 Translation updates across all languages
  config/locales/collections/de.yml
  config/locales/collections/es.yml
  config/locales/collections/fr.yml
  config/locales/collections/nl.yml
  config/locales/collections/pl.yml
  config/locales/creators/de.yml
  config/locales/creators/es.yml
  config/locales/creators/fr.yml
  config/locales/creators/nl.yml
  config/locales/creators/pl.yml
  config/locales/de.yml
  config/locales/devise/fr.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/libraries/de.yml
  config/locales/libraries/es.yml
  config/locales/libraries/fr.yml
  config/locales/libraries/nl.yml
  config/locales/libraries/pl.yml
  config/locales/model_files/fr.yml
  config/locales/models/de.yml
  config/locales/models/es.yml
  config/locales/models/fr.yml
  config/locales/models/nl.yml
  config/locales/models/pl.yml
  config/locales/nl.yml
  config/locales/pl.yml
  config/locales/problems/fr.yml
  config/locales/settings/de.yml
  config/locales/settings/es.yml
  config/locales/settings/fr.yml
  config/locales/settings/nl.yml
  config/locales/settings/pl.yml
Labels: improvement, localisation

#3614 Handle listing models for tags that include commas
  app/controllers/concerns/filterable.rb
Labels: bug

#3615 Fix tags with ampersands in bulk edit dropdown remove list
  app/javascript/src/bulk_edit.ts
Labels: bug

#3629 Fix search error for contributors and members
  app/controllers/concerns/model_listable.rb
Labels: bug

#3628 Add a Dev Container
  .devcontainer/devcontainer.json
  README.md
Labels: improvement

#3632 Translation updates (DE, PL, ES)
  config/locales/de.yml
  config/locales/es.yml
  config/locales/libraries/de.yml
  config/locales/libraries/es.yml
  config/locales/libraries/pl.yml
  config/locales/pl.yml
  config/locales/settings/de.yml
  config/locales/settings/es.yml
  config/locales/settings/pl.yml
Labels: improvement, localisation

#3635 Fix clashing background colour on usage report data
  app/views/settings/reporting.html.erb
Labels: bug, accessibility

#3641 Drop 32-bit ARM builds
  .github/workflows/docker.yml
Labels: improvement, breaking change

#3640 Add Creator field to Collections and allow Collections to be filtered by Creator
  app/controllers/collections_controller.rb
  app/controllers/concerns/filterable.rb
  app/models/collection.rb
  app/models/creator.rb
  app/serializers/activity_pub/collection_serializer.rb
  app/views/collections/_collection.html.erb
  app/views/collections/_form.html.erb
  app/views/collections/index.html.erb
  app/views/creators/_creator.html.erb
  db/data_schema.rb
  db/migrate/20250222000000_add_creator_to_collections.rb
  db/schema.rb
Labels: feature

#3654 Enforce access policy on collection and creator lists
  app/controllers/collections_controller.rb
  app/views/collections/index.html.erb
Labels: bug

#3655 Fix links to creator collection list
  app/views/collections/_collection.html.erb
  app/views/creators/_creator.html.erb
Labels: bug

#3658 Add password strength meter, and link to strength configuration on first use
  app/helpers/application_helper.rb
  app/javascript/application.ts
  app/javascript/src/passwords.ts
  app/views/devise/passwords/edit.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/first_use.html.erb
  app/views/devise/registrations/new.html.erb
  config/locales/devise/en.yml
  package.json
  yarn.lock
Labels: feature

#3634 Store metadata in file on disk
  app/jobs/update_datapackage_job.rb
  app/models/model.rb
  app/models/model_file.rb
  app/serializers/data_package/base_serializer.rb
  app/serializers/data_package/creator_serializer.rb
  app/serializers/data_package/model_file_serializer.rb
  app/serializers/data_package/model_serializer.rb
  spec/jobs/update_datapackage_job_spec.rb
  spec/serializers/data_package/creator_serializer_spec.rb
  spec/serializers/data_package/model_file_serializer_spec.rb
  spec/serializers/data_package/model_serializer_spec.rb
Labels: feature

#3665 include metadata datapackage file in downloads
  app/controllers/models_controller.rb
Labels: feature

#3669 Fix bug in problem finder method
  app/helpers/models_helper.rb
Labels: bug

#3671 Improve docs for volume line in docker example file
  docker-compose.example.yml
Labels: documentation, improvement

#3674 Improve datapackage file creation
  app/jobs/update_datapackage_job.rb
Labels: bug

#3675 Add upgrade job to backfill datapackages in the background
  app/jobs/update_datapackage_job.rb
  app/jobs/upgrade/backfill_data_packages.rb
  config/initializers/upgrade.rb
Labels: improvement

#3677 Add rubocop-pundit safety checks for use of #all
  Gemfile.lock
  app/controllers/activity_controller.rb
  app/controllers/application_controller.rb
  app/helpers/problems_helper.rb
  app/views/application/_navbar.html.erb
  app/views/models/_form.html.erb
  app/views/models/bulk_edit.html.erb
  app/views/models/new.html.erb
  app/views/settings/users/_form.html.erb
  spec/helpers/problems_helper_spec.rb
Labels: improvement, security

#3678 Change job iteration method from sidekiq to activejob
  Gemfile
  Gemfile.lock
  app/jobs/upgrade/fix_nil_file_size_values.rb
  config/initializers/upgrade.rb
  spec/jobs/upgrade/fix_nil_file_size_values_spec.rb
Labels: improvement

#3682 Make sure datapackage.json isn't listed in resources
  app/serializers/data_package/model_file_serializer.rb
  app/serializers/data_package/model_serializer.rb
  spec/jobs/update_datapackage_job_spec.rb
Labels: bug
