Repository manyfold3d/manyfold, pull requests merged in 2025-01, with the labels that each got.

#3352 Add shadowed rendering mode using an SSAO pass
  app/javascript/offscreen_renderer.ts
  app/views/devise/registrations/_renderer_settings.html.erb
  config/locales/devise/de.yml
  config/locales/devise/en.yml
  config/locales/devise/es.yml
  config/locales/devise/fr.yml
  config/locales/devise/pl.yml
Labels: feature

#3353 Fix scan failure when library path contains a space
  app/models/library.rb
  spec/jobs/model_scan_job_spec.rb
  spec/jobs/scan/detect_filesystem_changes_job_spec.rb
  spec/models/library_spec.rb
Labels: bug

#3354 Fix error when auto-creating federation actors
  app/models/concerns/federails_common.rb
  app/models/concerns/followable.rb
  app/models/concerns/follower.rb
Labels: bug

#3367 Update to Ruby 3.4
  .ruby-version
  Gemfile.lock
  docker/base.dockerfile
Labels: dependencies

#3369 Improved syntax for single-arg block parameters
  .rubocop.yml
  app/controllers/activity_controller.rb
  app/controllers/follows_controller.rb
  app/controllers/models_controller.rb
  app/helpers/models_helper.rb
  app/jobs/analysis/analyse_model_file_job.rb
  app/jobs/analysis/file_conversion_job.rb
  app/jobs/model_scan_job.rb
  app/jobs/process_uploaded_file_job.rb
  app/models/concerns/followable.rb
  app/models/concerns/path_builder.rb
  app/models/concerns/path_parser.rb
  db/data/20230628194944_make_names_unique.rb
  db/data/20240615085913_move_file_data_into_shrine.rb
  spec/jobs/analysis/analyse_model_file_job_spec.rb
  spec/models/problem_spec.rb
  spec/requests/models_spec.rb
Labels: improvement

#3373 Fix error viewing OIDC users
  app/views/settings/users/show.html.erb
Labels: bug

#3376 Translation updates across DE, PL, ES and lots for FR
  config/locales/collections/fr.yml
  config/locales/collections/pl.yml
  config/locales/creators/fr.yml
  config/locales/de.yml
  config/locales/devise/de.yml
  config/locales/devise/fr.yml
  config/locales/devise/pl.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/libraries/fr.yml
  config/locales/model_files/fr.yml
  config/locales/models/fr.yml
  config/locales/pl.yml
  config/locales/problems/fr.yml
  config/locales/settings/de.yml
  config/locales/settings/es.yml
  config/locales/settings/fr.yml
  config/locales/settings/pl.yml
Labels: improvement, localisation

#3374 Specify Node version for Volta tool
  package.json
Labels: improvement

#3384 Resumable uploads using Tus
  Gemfile
  Gemfile.lock
  app/controllers/model_files_controller.rb
  app/controllers/models_controller.rb
  app/javascript/src/uploads.ts
  app/jobs/cache_sweep_job.rb
  app/uploaders/library_uploader.rb
  config/initializers/shrine.rb
  config/routes.rb
  package.json
  yarn.lock
Labels: feature

#3399 Fix docker builds by adding missing packages
  docker/build.dockerfile
Labels: bug

#3398 Refactor comment code to use new Federails data entity system
  Gemfile
  Gemfile.lock
  app/models/comment.rb
  db/migrate/20250114105808_add_federation_attributes_to_comments.rb
  db/schema.rb
  spec/models/comment_spec.rb
Labels: improvement

#3406 Load all possible SMTP settings from environment vars
  config/application.rb
Labels: feature

#3408 Re-add block parameters for Ruby 3.3 compatibility (fixes linuxserver images)
  app/controllers/activity_controller.rb
  app/controllers/models_controller.rb
  app/helpers/models_helper.rb
  app/jobs/analysis/analyse_model_file_job.rb
  app/jobs/analysis/file_conversion_job.rb
  app/jobs/model_scan_job.rb
  app/jobs/process_uploaded_file_job.rb
  app/models/concerns/followable.rb
  app/models/concerns/path_builder.rb
  app/models/concerns/path_parser.rb
  db/data/20230628194944_make_names_unique.rb
  db/data/20240615085913_move_file_data_into_shrine.rb
  spec/jobs/analysis/analyse_model_file_job_spec.rb
  spec/models/problem_spec.rb
  spec/requests/models_spec.rb
Labels: bug

#3409 Rename some more block variables to ease future updates
  app/admin/collections.rb
  app/admin/creators.rb
  app/admin/libraries.rb
  app/admin/model_files.rb
  app/admin/models.rb
  app/admin/users.rb
  app/controllers/activity_controller.rb
  app/helpers/uploads_helper.rb
  app/jobs/scan/detect_filesystem_changes_job.rb
  app/models/library.rb
  app/models/model_file.rb
  app/models/user.rb
  app/views/libraries/_form.html.erb
  app/views/problems/_filters.html.erb
  config/initializers/activejob_status.rb
  spec/helpers/models_helper_spec.rb
Labels: improvement

#3401 Fix setting the provided password when creating an account when no SMTP server is configured.
  app/controllers/settings/users_controller.rb
  spec/requests/settings/users_spec.rb
Labels: bug

#3410 Fix missing icons in feed
  app/views/activities/_create_actor.html.erb
Labels: bug

#3415 Set SSL verify mode as string, not symbol
  config/application.rb
Labels: bug

#3416 File renaming
  app/controllers/model_files_controller.rb
  app/models/model_file.rb
  app/validators/change_case_only_validator.rb
  app/validators/stable_mime_type_validator.rb
  app/views/model_files/_form.html.erb
  config/locales/en.yml
  spec/models/model_file_spec.rb
Labels: feature

#3417 Use full file path for grouping inside models
  app/helpers/models_helper.rb
Labels: feature

#3418 Index Prusa's Binary GCode (.bgcode) files
  config/initializers/mime_types.rb
Labels: feature

#3419 Include archive files when indexing existing files on disk
  app/helpers/uploads_helper.rb
  app/lib/supported_mime_types.rb
Labels: feature

#3420 Index HTML and Word documents
  app/lib/supported_mime_types.rb
  config/initializers/mime_types.rb
  spec/lib/supported_mime_types_spec.rb
Labels: feature

#3421 Dynamically set file grouping size based on number of files
  app/helpers/models_helper.rb
  app/views/models/show.html.erb
Labels: feature

#3422 Add a form helper for checkbox inputs
  app/helpers/application_helper.rb
Labels: improvement

#3425 Rename files in bulk
  app/controllers/model_files_controller.rb
  app/views/model_files/bulk_edit.html.erb
  spec/requests/model_files_spec.rb
Labels: feature

#3426 Fix missing breadcrumb on file edit page
  app/views/model_files/_breadcrumb.html.erb
Labels: bug

#3427 Use checkbox row helper
  app/views/model_files/_form.html.erb
  app/views/model_files/bulk_edit.html.erb
  app/views/models/_bulk_fields.html.erb
  app/views/models/_form.html.erb
  app/views/models/bulk_edit.html.erb
Labels: improvement

#3436 Fix display of "printed" state
  app/helpers/application_helper.rb
  app/models/user.rb
Labels: bug

#3438 Add translations for bulk file renaming fields
  app/helpers/application_helper.rb
  app/views/model_files/bulk_edit.html.erb
  config/locales/model_files/de.yml
  config/locales/model_files/en.yml
  config/locales/model_files/es.yml
  config/locales/model_files/fr.yml
  config/locales/model_files/nl.yml
  config/locales/model_files/pl.yml
Labels: improvement, localisation

#3439 Add total model count to update all button
  app/views/models/bulk_edit.html.erb
  config/locales/models/en.yml
Labels: improvement

#3443 Minor translation updates
  config/locales/de.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/model_files/de.yml
  config/locales/model_files/es.yml
  config/locales/pl.yml
Labels: improvement, localisation

#3444 Minor polish translation update
  config/locales/model_files/pl.yml
Labels: improvement, localisation

#3445 Add support for Fusion360 and Inventor files
  config/initializers/mime_types.rb
Labels: feature

#3446 Fix "update all" button
  app/controllers/models_controller.rb
  app/views/models/bulk_edit.html.erb
  spec/requests/models_spec.rb
Labels: bug

#3448 Fix errors when merging models
  app/models/model_file.rb
Labels: bug

#3449 Fix error when members try to report models
  app/controllers/reports_controller.rb
  app/policies/federails/moderation/report_policy.rb
Labels: bug

#3450 Don't show site settings link to members
  app/views/application/_navbar.html.erb
Labels: bug

#3458 Add option for whether or not to use path-style URLs for non-AWS S3 services
  app/helpers/application_helper.rb
  app/models/library.rb
  app/views/libraries/_form.html.erb
  config/locales/en.yml
  config/locales/libraries/en.yml
  db/migrate/20250121105010_add_s3_path_style_to_library.rb
  db/schema.rb
Labels: bug

#3459 Fix s3 path-style parameter filtering
  app/admin/libraries.rb
  app/controllers/libraries_controller.rb
Labels: bug

#3461 Fix case-sensitivity in public IDs
  app/models/concerns/public_i_dable.rb
  db/data/20250121164452_make_public_i_ds_lowercase.rb
Labels: bug

#3465 add SUDO_RUN_UNSAFELY env var to disable root security warning
  app/controllers/application_controller.rb
Labels: feature, security

#3467 Configure SSL and hostname in dev mode for use with ngrok tunnels
  config/environments/development.rb
Labels: improvement

#3468 Add concrete type to User activitystreams representation
  app/models/user.rb
Labels: improvement, federation

#3469 Add trust & safety category to release notes
  .github/release.yml
Labels: documentation, improvement

#3470 Fix unfollowing remote actors
  app/components/follow_button_component.rb
  app/controllers/follows_controller.rb
  app/models/concerns/follower.rb
  config/locales/en.yml
  config/routes.rb
Labels: bug

#3472 Store activitypub extension data for remote actors
  Gemfile
  Gemfile.lock
  db/migrate/20250122171731_add_extensions_to_federails_actors.federails.rb
  db/schema.rb
Labels: improvement

#3473 Include creator caption and notes in activitystream summary
  app/models/creator.rb
  spec/factories/creator.rb
  spec/models/creator_spec.rb
Labels: improvement, federation

#3477 Add creator links as attachments in activitystreams
  app/models/creator.rb
  spec/factories/creator.rb
  spec/models/creator_spec.rb
Labels: improvement, federation

#3478 Include followed remote creators in list
  Gemfile
  Gemfile.lock
  app/controllers/follows_controller.rb
  app/models/concerns/federails_common.rb
  app/models/creator.rb
  app/views/creators/_creator.html.erb
  app/views/creators/show.html.erb
  config/locales/creators/en.yml
Labels: feature, federation

#3481 Order libraries by name, by default
  app/models/library.rb
Labels: improvement

#3482 Reorganise creator display a little for remote creators
  app/views/creators/_creator.html.erb
  app/views/creators/show.html.erb
  config/locales/creators/en.yml
Labels: improvement

#3483 Rename extension namespace to f3di
  app/controllers/follows_controller.rb
  app/models/creator.rb
  app/models/user.rb
  spec/models/creator_spec.rb
Labels: improvement, federation

#3488 Fix problems with searching for remote fediverse users
  Gemfile
  Gemfile.lock
  app/controllers/follows_controller.rb
  app/models/creator.rb
  app/views/creators/_creator.html.erb
  app/views/creators/show.html.erb
  app/views/models/show.html.erb
  spec/requests/webfinger_spec.rb
Labels: bug, federation

#3489 Use simpler regexp output for file settings form
  app/views/settings/_file_settings.html.erb
Labels: bug

#3490 Entering fediverse username in main search redirects to follow page
  app/controllers/models_controller.rb
  app/views/follows/new.html.erb
  config/locales/en.yml
Labels: feature

#3491 Deliver creator updates to its followers
  Gemfile
  Gemfile.lock
  app/models/concerns/followable.rb
Labels: improvement

#3497 Refactor ActivityPub rendering code into presenters
  app/models/comment.rb
  app/models/creator.rb
  app/presenters/activity_pub/base_presenter.rb
  app/presenters/activity_pub/comment_presenter.rb
  app/presenters/activity_pub/creator_presenter.rb
Labels: improvement

#3498 Rename ActivityPub presenters to serializers
  app/models/comment.rb
  app/models/creator.rb
  app/serializers/activity_pub/base_serializer.rb
  app/serializers/activity_pub/comment_serializer.rb
  app/serializers/activity_pub/creator_serializer.rb
Labels: improvement

#3499 Move user serialization into its own class
  app/models/user.rb
  app/serializers/activity_pub/user_serializer.rb
Labels: improvement

#3500 Only auto accept follows for local objects
  app/models/concerns/followable.rb
Labels: bug

#3502 Add serializers for Model and Collection, to be used in future
  app/models/collection.rb
  app/models/comment.rb
  app/models/concerns/caber_object.rb
  app/models/model.rb
  app/models/user.rb
  app/serializers/activity_pub/application_serializer.rb
  app/serializers/activity_pub/collection_serializer.rb
  app/serializers/activity_pub/comment_serializer.rb
  app/serializers/activity_pub/creator_serializer.rb
  app/serializers/activity_pub/model_serializer.rb
  app/serializers/activity_pub/user_serializer.rb
  spec/models/creator_spec.rb
  spec/requests/webfinger_spec.rb
Labels: improvement

#3510 Test and parse model tags in activitypub
  app/deserializers/activity_pub/model_deserializer.rb
  spec/deserializers/activity_pub/model_deserializer_spec.rb
  spec/factories/federails/actor.rb
  spec/serializers/activity_pub/model_serializer_spec.rb
Labels: improvement

#3511 Follow remote models and collections
  app/controllers/collections_controller.rb
  app/views/collections/_collection.html.erb
  app/views/collections/show.html.erb
  app/views/creators/show.html.erb
  app/views/models/show.html.erb
  config/locales/collections/en.yml
  spec/requests/collections_spec.rb
Labels: feature, federation

#3514 Fix collection page bug
  app/views/collections/show.html.erb
Labels: bug

#3516 Show user fedi address on settings page
  app/views/devise/registrations/edit.html.erb
Labels: feature, federation

#3517 Add flag for notes generated for compatibility purposes
  app/serializers/activity_pub/comment_serializer.rb
Labels: improvement, federation

#3527 Revert "Bump aws-sdk-s3 from 1.177.0 to 1.179.0"
  Gemfile
  Gemfile.lock
Labels: dependencies
