Repository manyfold3d/manyfold, pull requests merged in 2025-04, with the labels that each got.

#3900 Add following/follower lists
  app/controllers/follows_controller.rb
  app/models/concerns/follower.rb
  app/views/devise/registrations/edit.html.erb
  app/views/follows/_actor_table.html.erb
  app/views/follows/index.html.erb
  config/locales/devise/en.yml
  config/locales/en.yml
Labels: feature

#3901 Remove unused translations from non-en languages
  config/locales/cs.yml
  config/locales/de.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/nl.yml
  config/locales/pl.yml
Labels: bug, localisation

#3907 Refactor scanning jobs to make them easier to understand and navigate
  app/controllers/libraries_controller.rb
  app/controllers/model_files_controller.rb
  app/controllers/models_controller.rb
  app/controllers/problems_controller.rb
  app/jobs/analysis/analyse_model_file_job.rb
  app/jobs/analysis/file_conversion_job.rb
  app/jobs/process_uploaded_file_job.rb
  app/jobs/scan/check_all_job.rb
  app/jobs/scan/check_model_job.rb
  app/jobs/scan/library/create_model_from_path_job.rb
  app/jobs/scan/library/detect_filesystem_changes_job.rb
  app/jobs/scan/model/add_new_files_job.rb
  app/jobs/scan/model/check_for_problems_job.rb
  app/jobs/scan/model/parse_metadata_job.rb
  app/jobs/scan/model_file/parse_metadata_job.rb
  app/jobs/upgrade/backfill_data_packages.rb
  app/models/library.rb
  app/models/model.rb
  app/models/model_file.rb
  spec/jobs/process_uploaded_file_job_spec.rb
  spec/jobs/scan/check_model_job_spec.rb
  spec/jobs/scan/library/create_model_from_path_job_spec.rb
  spec/jobs/scan/library/detect_filesystem_changes_job_spec.rb
  spec/jobs/scan/model/add_new_files_job_spec.rb
  spec/jobs/scan/model/check_for_problems_job_spec.rb
  spec/jobs/scan/model/parse_metadata_job_spec.rb
  spec/jobs/scan/model_file/parse_metadata_job_spec.rb
  spec/requests/libraries_spec.rb
  spec/requests/models_spec.rb
Labels: improvement

#3908 Add support for `hfp` format of Hue Forge
  app/lib/supported_mime_types.rb
  config/initializers/mime_types.rb
Labels: feature

#3909 Refactor metadata parsing in preparation for datapackage parsing
  app/jobs/scan/model/parse_metadata_job.rb
  app/models/concerns/path_parser.rb
  app/models/model.rb
  app/services/path_parser_service.rb
  spec/jobs/scan/model/parse_metadata_job_spec.rb
  spec/models/concerns/path_parser_spec.rb
  spec/services/path_parser_service_spec.rb
Labels: improvement

#3906 Add "open in Elegoo Slicer"
  app/controllers/application_controller.rb
  app/helpers/model_files_helper.rb
  config/locales/model_files/en.yml
  spec/helpers/model_files_helper_spec.rb
Labels: feature

#3914 Added README doc for background job dependencies
  app/jobs/README.md
Labels: documentation, improvement

#3916 Add datapackage deserializer
  app/deserializers/data_package/base_deserializer.rb
  app/deserializers/data_package/creator_deserializer.rb
  app/deserializers/data_package/model_deserializer.rb
  app/deserializers/data_package/model_file_deserializer.rb
  spec/deserializers/data_package/creator_deserializer_spec.rb
  spec/deserializers/data_package/model_deserializer_spec.rb
  spec/deserializers/data_package/model_file_deserializer_spec.rb
  spec/serializers/data_package/creator_serializer_spec.rb
  spec/serializers/data_package/model_file_serializer_spec.rb
  spec/serializers/data_package/model_serializer_spec.rb
Labels: improvement

#3917 Add datapackage files when scanning disk
  app/jobs/scan/model/add_new_files_job.rb
  spec/jobs/scan/model/add_new_files_job_spec.rb
Labels: improvement

#3922 Decrease upload chunk size to 1M to match nginx default
  app/javascript/src/uploads.ts
Labels: improvement

#3918 Use metadata from datapackages, both on upload and on scan
  app/deserializers/data_package/model_file_deserializer.rb
  app/jobs/scan/model/parse_metadata_job.rb
  app/serializers/data_package/model_serializer.rb
  spec/deserializers/data_package/model_file_deserializer_spec.rb
Labels: feature

#3892 Set model updated time when files are updated
  app/models/model_file.rb
Labels: improvement

#3925 Open in Superslicer
  app/helpers/model_files_helper.rb
  config/locales/model_files/cs.yml
  config/locales/model_files/de.yml
  config/locales/model_files/en.yml
  config/locales/model_files/es.yml
  config/locales/model_files/fr.yml
  config/locales/model_files/nl.yml
  config/locales/model_files/pl.yml
  spec/helpers/model_files_helper_spec.rb
Labels: feature

#3928 Add delete button on image carousel
  app/views/models/_image_carousel.html.erb
Labels: feature

#3944 Federails 0.6: ActivityPub "Delete" activities, unfollowing, and more improvements.
  Gemfile
  Gemfile.lock
  app/jobs/upgrade/update_actors_job.rb
  config/initializers/upgrade.rb
  db/data_schema.rb
  db/migrate/20250407160721_add_actor_type_to_actors.federails.rb
  db/migrate/20250407160722_add_tombstoned_at_to_actors.federails.rb
  db/schema.rb
  spec/factories/federails/actor.rb
Labels: improvement

#3949 Added "Brite" theme
  app/assets/stylesheets/entrypoints/themes/brite.scss
  app/views/settings/appearance.html.erb
Labels: feature

#3951 Add API authentication using OAuth2 Client Credentials flow
  Gemfile
  Gemfile.lock
  app/api/v0/openapi.json
  app/controllers/application_controller.rb
  app/controllers/doorkeeper_applications_controller.rb
  app/models/user.rb
  app/policies/doorkeeper/application_policy.rb
  app/views/doorkeeper_applications/_breadcrumb.html.erb
  app/views/doorkeeper_applications/_form.html.erb
  app/views/doorkeeper_applications/edit.html.erb
  app/views/doorkeeper_applications/index.html.erb
  app/views/doorkeeper_applications/new.html.erb
  app/views/doorkeeper_applications/show.html.erb
  app/views/layouts/settings.html.erb
  config/initializers/doorkeeper.rb
  config/locales/doorkeeper.en.yml
  config/locales/en.yml
  config/routes.rb
  db/migrate/20250408111644_create_doorkeeper_tables.rb
  db/migrate/20250408145956_add_owner_to_application.rb
  db/schema.rb
  spec/factories/doorkeeper/access_token.rb
  spec/factories/doorkeeper/application.rb
  spec/requests/api/json_ld/collections_spec.rb
  spec/requests/api/json_ld/creators_spec.rb
  spec/requests/api/json_ld/model_files_spec.rb
  spec/requests/api/json_ld/models_spec.rb
  spec/swagger_helper.rb
Labels: feature

#3952 Remove ability to generate long-lived bearer tokens
  app/controllers/doorkeeper_applications_controller.rb
  app/views/doorkeeper_applications/show.html.erb
  config/locales/en.yml
  spec/swagger_helper.rb
Labels: improvement, security

#3953 Add .sldprt file handling
  app/lib/supported_mime_types.rb
  config/initializers/mime_types.rb
Labels: feature

#3954 update federails
  Gemfile.lock
Labels: dependencies

#3960 Fix some problems with actor database inconsistency
  Gemfile
  Gemfile.lock
  app/jobs/upgrade/update_actors_job.rb
  db/migrate/20250409120155_remove_default_actor_entity_type.rb
  db/schema.rb
Labels: bug

#3966 Refactor: add :after_first_run metadata for test setup
  spec/jobs/process_uploaded_file_job_spec.rb
  spec/requests/api/json_ld/collections_spec.rb
  spec/requests/api/json_ld/creators_spec.rb
  spec/requests/api/json_ld/model_files_spec.rb
  spec/requests/api/json_ld/models_spec.rb
  spec/requests/api/oembed/collections_spec.rb
  spec/requests/api/oembed/creators_spec.rb
  spec/requests/api/oembed/models_spec.rb
  spec/requests/model_files_spec.rb
  spec/requests/models_spec.rb
  spec/support/features.rb
Labels: improvement

#3967 Doorkeeper configuration improvements
  config/initializers/doorkeeper.rb
Labels: improvement, security

#3970 Add support for enforcing scopes on API calls
  app/api/v0/openapi.json
  app/controllers/application_controller.rb
  app/controllers/collections_controller.rb
  app/controllers/creators_controller.rb
  app/controllers/model_files_controller.rb
  app/controllers/models_controller.rb
  config/initializers/doorkeeper.rb
  spec/requests/api/json_ld/collections_spec.rb
  spec/requests/api/json_ld/creators_spec.rb
  spec/requests/api/json_ld/model_files_spec.rb
  spec/requests/api/json_ld/models_spec.rb
  spec/swagger_helper.rb
Labels: feature, security

#3972 Add Rswag configuration to code linter
  .rubocop.yml
  spec/factories/library.rb
  spec/factories/model.rb
  spec/requests/api/json_ld/collections_spec.rb
  spec/requests/api/json_ld/creators_spec.rb
  spec/requests/api/json_ld/model_files_spec.rb
  spec/requests/api/json_ld/models_spec.rb
  spec/requests/api/oembed/api_endpoint_spec.rb
  spec/requests/api/oembed/collections_spec.rb
  spec/requests/api/oembed/creators_spec.rb
  spec/requests/api/oembed/models_spec.rb
  spec/support/parsed_body.rb
Labels: improvement

#3976 Add tests for public vs read scope on lists
  .rubocop.yml
  spec/requests/api/v0/collections_spec.rb
  spec/requests/api/v0/creators_spec.rb
  spec/requests/api/v0/models_spec.rb
Labels: improvement

#3977 Skip CSRF protection on API requests
  app/controllers/application_controller.rb
Labels: improvement

#3968 Write & Delete API actions for Creators
  app/api/v0/openapi.json
  app/controllers/collections_controller.rb
  app/controllers/creators_controller.rb
  app/controllers/model_files_controller.rb
  app/controllers/models_controller.rb
  spec/factories/doorkeeper/application.rb
  spec/requests/api/v0/collections_spec.rb
  spec/requests/api/v0/creators_spec.rb
  spec/requests/api/v0/model_files_spec.rb
  spec/requests/api/v0/models_spec.rb
Labels: feature

#3978 Create and edit creators and collections via API
  app/api/v0/openapi.json
  app/controllers/collections_controller.rb
  app/controllers/creators_controller.rb
  app/deserializers/manyfold_api/v0/base_deserializer.rb
  app/deserializers/manyfold_api/v0/collection_deserializer.rb
  app/deserializers/manyfold_api/v0/creator_deserializer.rb
  app/serializers/manyfold_api/v0/creator_serializer.rb
  config/initializers/parameter_parsers.rb
  spec/factories/doorkeeper/application.rb
  spec/requests/api/oembed/collections_spec.rb
  spec/requests/api/oembed/creators_spec.rb
  spec/requests/api/oembed/models_spec.rb
  spec/requests/api/v0/collections_spec.rb
  spec/requests/api/v0/creators_spec.rb
  spec/requests/api/v0/models_spec.rb
  spec/swagger_helper.rb
Labels: feature

#3979 Edit models and file metadata via API
  .rubocop.yml
  app/api/v0/openapi.json
  app/controllers/model_files_controller.rb
  app/controllers/models_controller.rb
  app/deserializers/manyfold_api/v0/model_deserializer.rb
  app/deserializers/manyfold_api/v0/model_file_deserializer.rb
  spec/requests/api/v0/model_files_spec.rb
  spec/requests/api/v0/models_spec.rb
  spec/swagger_helper.rb
Labels: feature

#3982 Refactor form parameters into deserializer objects
  app/controllers/collections_controller.rb
  app/controllers/creators_controller.rb
  app/controllers/model_files_controller.rb
  app/controllers/models_controller.rb
  app/deserializers/form/base_deserializer.rb
  app/deserializers/form/collection_deserializer.rb
  app/deserializers/form/creator_deserializer.rb
  app/deserializers/form/model_deserializer.rb
  app/deserializers/form/model_file_deserializer.rb
Labels: improvement

#3988 Add remaining creator, collection, model and file fields to API
  .rubocop.yml
  app/api/v0/openapi.json
  app/deserializers/manyfold_api/v0/base_deserializer.rb
  app/deserializers/manyfold_api/v0/collection_deserializer.rb
  app/deserializers/manyfold_api/v0/creator_deserializer.rb
  app/deserializers/manyfold_api/v0/link_deserializer.rb
  app/deserializers/manyfold_api/v0/model_deserializer.rb
  app/deserializers/manyfold_api/v0/model_file_deserializer.rb
  app/serializers/manyfold_api/v0/application_serializer.rb
  app/serializers/manyfold_api/v0/collection_serializer.rb
  app/serializers/manyfold_api/v0/creator_serializer.rb
  app/serializers/manyfold_api/v0/link_serializer.rb
  app/serializers/manyfold_api/v0/model_file_serializer.rb
  app/serializers/manyfold_api/v0/model_serializer.rb
  spec/requests/api/v0/collections_spec.rb
  spec/requests/api/v0/model_files_spec.rb
  spec/requests/api/v0/models_spec.rb
  spec/serializers/manyfold_api/v0/model_list_serializer_spec.rb
  spec/swagger_helper.rb
Labels: feature

#3990 Check that JSON-LD responses produce valid RDF
  spec/requests/api/v0/collections_spec.rb
  spec/requests/api/v0/creators_spec.rb
  spec/requests/api/v0/model_files_spec.rb
  spec/requests/api/v0/models_spec.rb
Labels: improvement

#3992 Remove unused doorkeeper translation file
  config/locales/doorkeeper.en.yml
Labels: improvement

#3991 Add scope selection to OAuth app UI
  app/controllers/doorkeeper_applications_controller.rb
  app/views/doorkeeper_applications/_form.html.erb
  app/views/doorkeeper_applications/show.html.erb
  config/locales/en.yml
Labels: feature

#3996 Restrict preview file selection to only image or renderable 3d files
  app/models/model.rb
  app/views/models/_form.html.erb
Labels: bug

#3997 Change to Github Flavoured Markdown parser
  Gemfile
  Gemfile.lock
  app/helpers/application_helper.rb
  app/serializers/activity_pub/comment_serializer.rb
Labels: bug

#3998 Add help text to indicate that s3 endpoint needs complete URL, including scheme
  config/locales/libraries/en.yml
Labels: improvement

#4008 Allow re-parsing of data when a creator is set, without overwriting it.
  app/jobs/scan/model/parse_metadata_job.rb
  spec/jobs/scan/model/parse_metadata_job_spec.rb
Labels: bug

#4009 Fix problem not saving file ignore regexes
  app/controllers/settings_controller.rb
  spec/requests/settings_spec.rb
Labels: bug

#4010 Deduplicate links when loading metadata from datapackages
  app/jobs/scan/model/parse_metadata_job.rb
  app/models/model.rb
  spec/jobs/scan/model/parse_metadata_job_spec.rb
  spec/jobs/update_datapackage_job_spec.rb
Labels: bug

#4011 Preserve file created/modified times during upload and download
  app/controllers/models_controller.rb
  app/models/model_file.rb
  app/uploaders/library_uploader.rb
  config/initializers/libarchive_security.rb
Labels: bug

#4014 Improve job documentation
  app/jobs/README.md
Labels: documentation, improvement

#4016 Fix ignored file regex input, and improve some help text
  app/controllers/settings_controller.rb
  app/views/settings/_file_settings.html.erb
  config/locales/settings/en.yml
Labels: bug

#4018 Fail safely when parsing metadata if datapackage file is missing
  app/models/model.rb
Labels: bug

#4020 Fix carousel pause button
  app/javascript/src/carousel.ts
  config/locales/en.yml
Labels: bug, accessibility

#4023 Change code coverage to use Codacy instead of CodeClimate
  .github/workflows/push.yml
  Gemfile
  Gemfile.lock
  README.md
  spec/rails_helper.rb
Labels: documentation, improvement

#4039 Add bin/manyfold management tool for advanced tasks
  .rubocop.yml
  bin/manyfold
Labels: feature

#4041 Add allowed option values for "problems purge" command
  bin/manyfold
Labels: improvement

#4042 Add CLI command to rerun metadata parsing
  bin/manyfold
Labels: feature

#4048 Add configuration for Brakeman security checks
  config/brakeman.ignore
  config/brakeman.yml
Labels: improvement, security

#4050 Move to official release of sqlite3-ar-regexp
  Gemfile
  Gemfile.lock
Labels: dependencies

#4049 Upgrade to Rails 8
  .gitignore
  Gemfile
  Gemfile.lock
  README.md
  app/controllers/concerns/filterable.rb
  app/controllers/concerns/permittable.rb
  app/controllers/doorkeeper_applications_controller.rb
  app/controllers/libraries_controller.rb
  app/controllers/models_controller.rb
  app/controllers/problems_controller.rb
  app/controllers/reports_controller.rb
  app/controllers/settings/domain_blocks_controller.rb
  app/controllers/settings/users_controller.rb
  app/models/library.rb
  bin/brakeman
  bin/rubocop
  bin/setup
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/core_extensions.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/usage_reports.rb
  config/puma.rb
  lib/assets/.keep
  lib/tasks/.keep
  public/400.html
  public/404.html
  public/406-unsupported-browser.html
  public/422.html
  public/500.html
Labels: dependencies

#4058 Import notes from "README" files
  app/jobs/scan/model/parse_metadata_job.rb
  db/migrate/20250423094525_add_lowercase_filename_virtual_field_to_model_files.rb
  db/schema.rb
  spec/jobs/scan/model/parse_metadata_job_spec.rb
Labels: feature

#4060 Change "rescan all models" scan so that it re-parses metadata as well as checking problems
  app/jobs/README.md
  app/jobs/scan/check_all_job.rb
  app/jobs/scan/check_model_job.rb
  app/models/model.rb
  config/locales/en.yml
  spec/jobs/scan/check_model_job_spec.rb
  spec/requests/models_spec.rb
Labels: feature

#4062 Make sign in button more obvious
  app/views/application/_navbar.html.erb
Labels: improvement, UI / UX

#4063 add FEDERATION.md
  FEDERATION.md
Labels: documentation, improvement

#4064 Restyle sign in process to make it cleaner and more obvious
  Gemfile
  Gemfile.lock
  app/controllers/users/sessions_controller.rb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/home/index.html.erb
  app/views/layouts/application.html.erb
  app/views/models/_list.html.erb
  config/locales/devise/en.yml
  config/locales/models/en.yml
  config/locales/settings/en.yml
  spec/requests/users/sessions_spec.rb
Labels: improvement, UI / UX

#4067 Reject self links in datapackage parsing
  app/deserializers/data_package/model_deserializer.rb
  spec/deserializers/data_package/model_deserializer_spec.rb
Labels: bug

#4066 Parse metadata out of Thingiverse README files
  app/jobs/scan/model/parse_metadata_job.rb
  spec/jobs/scan/model/parse_metadata_job_spec.rb
Labels: feature

#4068 Fix ASCII conversion error when parsing READMEs
  app/jobs/scan/model/parse_metadata_job.rb
Labels: bug

#4069 Fix some unassigned preview files
  app/jobs/scan/model/parse_metadata_job.rb
Labels: bug

#4075 Ensure links are unique for each linkable object, plus a "manyfold links deduplicate" admin task
  app/jobs/scan/model/parse_metadata_job.rb
  app/models/concerns/linkable.rb
  app/models/link.rb
  bin/manyfold
  db/migrate/20250425104619_add_unique_index_to_links.rb
  db/schema.rb
  spec/models/link_spec.rb
  spec/models/model_spec.rb
Labels: bug

#4076 Don't write datapackages if model didn't change
  app/models/model.rb
  spec/models/model_spec.rb
Labels: bug

#4085 Reject empty urls in links
  app/components/link_component.rb
  app/models/concerns/linkable.rb
  app/models/link.rb
  app/views/application/_links_card.html.erb
  app/views/collections/_collection.html.erb
  app/views/creators/_creator.html.erb
  spec/models/link_spec.rb
Labels: bug

#4087 Don't update model file records unnecessarily
  app/controllers/models_controller.rb
  app/jobs/analysis/analyse_model_file_job.rb
Labels: bug
