Repository manyfold3d/manyfold, pull requests merged in 2025-08, with the labels that each got.

#4604 Allow registration of FASP providers
  Gemfile
  Gemfile.lock
  config/initializers/federails.rb
  config/routes.rb
  db/migrate/20250806142734_create_fasp_client_providers.fasp_client.rb
  db/schema.rb
Labels: feature

#4608 Add authentication wall over FASP provider configuration
  Gemfile
  Gemfile.lock
  config/initializers/fasp_client.rb
  spec/factories/providers.rb
  spec/requests/settings/fasp_providers_spec.rb
Labels: improvement, security

#4614 Add AI code guidance to contributor guide
  .github/CONTRIBUTING.md
Labels: documentation

#4616 Only enable FASP client capabilities if we have federation enabled
  config/routes.rb
Labels: improvement

#4633 Add three CERN licenses
  app/helpers/models_helper.rb
  config/locales/en.yml
  spec/helpers/models_helper_spec.rb
Labels: feature

#4640 Support underscores in MMF usernames
  app/deserializers/integrations/my_mini_factory/base_deserializer.rb
  spec/deserializers/integrations/my_mini_factory/creator_deserializer_spec.rb
Labels: bug

#4651 Fix Thingiverse error filtering case sensitivity
  app/jobs/scan/model/parse_metadata_job.rb
  spec/jobs/scan/model/parse_metadata_job_spec.rb
Labels: bug

#4660 Automatically synchronise translations and open PRs for changes
  .github/workflows/translation.yml
Labels: improvement

#4666 Translations updates
  config/locales/models/es.yml
  config/locales/problems/es.yml
Labels: improvement, localisation

#4665 Don't crash if about text is nil
  app/views/home/about.html.erb
Labels: bug

#4670 Replace deprecated unprocessable_entity
  app/controllers/collections_controller.rb
  app/controllers/creators_controller.rb
  app/controllers/doorkeeper_applications_controller.rb
  app/controllers/libraries_controller.rb
  app/controllers/model_files_controller.rb
  app/controllers/models_controller.rb
  app/controllers/settings/domain_blocks_controller.rb
  app/controllers/settings/users_controller.rb
  app/controllers/users/registrations_controller.rb
  config/initializers/devise.rb
  spec/requests/model_files_spec.rb
  spec/requests/settings/users_spec.rb
Labels: improvement

#4671 Prevent the replacement of search boxes on page refreshes
  app/views/application/_navbar.html.erb
  app/views/home/index.html.erb
Labels: bug
