Repository manyfold3d/manyfold, pull requests merged in 2025-03, with the labels that each got.

#3707 Quieten down SASS deprecation warnings.
  package.json
Labels: improvement

#3681 API test and documentation framework
  Gemfile
  Gemfile.lock
  app/api/v0/openapi.json
  app/views/application/_footer.html.erb
  config/initializers/rswag_api.rb
  config/initializers/rswag_ui.rb
  config/locales/en.yml
  config/routes.rb
  spec/api/nodeinfo_spec.rb
  spec/swagger_helper.rb
Labels: feature

#3721 Optimised database queries
  app/controllers/collections_controller.rb
  app/controllers/concerns/filterable.rb
  app/controllers/concerns/model_listable.rb
  app/controllers/creators_controller.rb
  app/controllers/models_controller.rb
  app/controllers/problems_controller.rb
  app/controllers/settings/users_controller.rb
  app/lib/timeline.rb
  config/environments/development.rb
  config/initializers/bullet.rb
Labels: improvement, performance

#3722 Fix model deletion error
  app/models/model.rb
  spec/models/model_spec.rb
Labels: bug

#3729 More query improvements
  app/controllers/model_files_controller.rb
  app/controllers/models_controller.rb
  config/initializers/bullet.rb
Labels: improvement, performance

#3731 Allow one and two character usernames
  app/models/user.rb
  spec/models/user_spec.rb
Labels: improvement

#3740 OEmbed support for model URLs
  app/api/v0/openapi.json
  app/controllers/collections_controller.rb
  app/controllers/creators_controller.rb
  app/controllers/model_files_controller.rb
  app/controllers/models_controller.rb
  app/helpers/application_helper.rb
  app/serializers/o_embed/application_serializer.rb
  app/serializers/o_embed/collection_serializer.rb
  app/serializers/o_embed/creator_serializer.rb
  app/serializers/o_embed/model_serializer.rb
  app/views/layouts/embed.html.erb
  app/views/model_files/embedded.html.erb
  app/views/models/show.html.erb
  config/initializers/mime_types.rb
  config/routes.rb
  spec/factories/collection.rb
  spec/factories/creator.rb
  spec/factories/model.rb
  spec/models/comment_spec.rb
  spec/models/creator_spec.rb
  spec/requests/api/nodeinfo_spec.rb
  spec/requests/api/oembed/api_endpoint_spec.rb
  spec/requests/api/oembed/collections_spec.rb
  spec/requests/api/oembed/creators_spec.rb
  spec/requests/api/oembed/models_spec.rb
  spec/requests/comments_spec.rb
  spec/requests/webfinger_spec.rb
  spec/serializers/activity_pub/collection_serializer_spec.rb
  spec/serializers/activity_pub/creator_serializer_spec.rb
  spec/serializers/activity_pub/generic_activity_pub_serializer_shared.rb
  spec/serializers/activity_pub/model_serializer_spec.rb
  spec/serializers/o_embed/collection_serializer_spec.rb
  spec/serializers/o_embed/creator_serializer_spec.rb
  spec/serializers/o_embed/generic_o_embed_serializer_shared.rb
  spec/serializers/o_embed/model_serializer_spec.rb
  spec/support/error_handling.rb
  spec/swagger_helper.rb
Labels: feature

#3763 Improve access tests
  app/controllers/model_files_controller.rb
  config/routes.rb
  spec/requests/activity_spec.rb
  spec/requests/admin/collections_spec.rb
  spec/requests/admin/creators_spec.rb
  spec/requests/admin/dashboard_spec.rb
  spec/requests/admin/link_spec.rb
  spec/requests/admin/model_files_spec.rb
  spec/requests/admin/models_spec.rb
  spec/requests/admin/problem_spec.rb
  spec/requests/admin/tags_spec.rb
  spec/requests/api/nodeinfo_spec.rb
  spec/requests/api/oembed/api_endpoint_spec.rb
  spec/requests/api/oembed/collections_spec.rb
  spec/requests/api/oembed/creators_spec.rb
  spec/requests/api/oembed/models_spec.rb
  spec/requests/collections_spec.rb
  spec/requests/creators_spec.rb
  spec/requests/libraries_spec.rb
  spec/requests/models_spec.rb
  spec/requests/problems_spec.rb
  spec/requests/uploads_spec.rb
  spec/requests/users/passwords_spec.rb
  spec/requests/users/registrations_spec.rb
  spec/requests/webfinger_spec.rb
  spec/support/error_handling.rb
Labels: improvement

#3764 Add oEmbed autodiscovery tags for creators and collections
  app/views/collections/show.html.erb
  app/views/creators/show.html.erb
Labels: feature

#3778 Signed download URLs for model files
  app/controllers/model_files_controller.rb
  spec/requests/model_files_spec.rb
Labels: improvement

#3779 Download straight into slicers from model detail page
  app/helpers/model_files_helper.rb
  app/views/model_files/show.html.erb
  config/locales/model_files/en.yml
  spec/helpers/model_files_helper_spec.rb
Labels: feature

#3786 Make file removal safer
  app/controllers/model_files_controller.rb
  app/controllers/problems_controller.rb
  app/models/model.rb
  app/models/model_file.rb
  app/uploaders/library_uploader.rb
  spec/models/model_file_spec.rb
  spec/models/model_spec.rb
Labels: bug

#3789 Ensure that library deletion doesn't remove files on disk
  app/uploaders/library_uploader.rb
  spec/models/library_spec.rb
Labels: improvement

#3790 Fix foreign key errors by removing default scope on files
  app/controllers/model_files_controller.rb
  app/controllers/models_controller.rb
  app/helpers/application_helper.rb
  app/jobs/update_datapackage_job.rb
  app/jobs/upgrade/backfill_data_packages.rb
  app/models/model.rb
  app/models/model_file.rb
  spec/jobs/model_scan_job_spec.rb
  spec/jobs/update_datapackage_job_spec.rb
  spec/models/model_spec.rb
Labels: bug

#3627 Delete library button added to library settings
  app/views/libraries/_form.html.erb
  config/locales/libraries/en.yml
  spec/requests/libraries_spec.rb
Labels: feature

#3791 Add dropdown menu for files including "open in slicer" actions
  app/views/models/_file.html.erb
  config/locales/models/en.yml
Labels: feature

#3792 Change rubocop includes to plugins
  .rubocop.yml
Labels: improvement

#3793 Absorb shrine error after library deletion
  app/controllers/libraries_controller.rb
Labels: bug

#3802 Fix signed urls (open in slicer) in single user mode
  app/controllers/application_controller.rb
  app/controllers/model_files_controller.rb
  spec/requests/model_files_spec.rb
Labels: bug

#3806 Improvements to testing across single/multi user
  spec/requests/models_spec.rb
  spec/requests/users/passwords_spec.rb
  spec/requests/users/registrations_spec.rb
  spec/requests/users/sessions_spec.rb
  spec/requests/webfinger_spec.rb
  spec/support/features.rb
Labels: improvement

#3800 Added API responses for public models, collections, and creators
  Gemfile
  Gemfile.lock
  app/api/v0/openapi.json
  app/controllers/collections_controller.rb
  app/controllers/creators_controller.rb
  app/controllers/model_files_controller.rb
  app/controllers/models_controller.rb
  app/serializers/json_ld/application_serializer.rb
  app/serializers/json_ld/collection_list_serializer.rb
  app/serializers/json_ld/collection_serializer.rb
  app/serializers/json_ld/creator_list_serializer.rb
  app/serializers/json_ld/creator_serializer.rb
  app/serializers/json_ld/model_file_serializer.rb
  app/serializers/json_ld/model_list_serializer.rb
  app/serializers/json_ld/model_serializer.rb
  config/initializers/api.rb
  config/initializers/cors.rb
  config/initializers/mime_types.rb
  spec/requests/api/json_ld/collections_spec.rb
  spec/requests/api/json_ld/creators_spec.rb
  spec/requests/api/json_ld/model_files_spec.rb
  spec/requests/api/json_ld/models_spec.rb
  spec/requests/api/oembed/collections_spec.rb
  spec/requests/api/oembed/creators_spec.rb
  spec/requests/api/oembed/models_spec.rb
  spec/serializers/json_ld/collection_list_serializer_spec.rb
  spec/serializers/json_ld/creator_list_serializer_spec.rb
  spec/serializers/json_ld/model_list_serializer_spec.rb
Labels: feature

#3814 Add license details to model and file APIs
  app/api/v0/openapi.json
  app/serializers/json_ld/application_serializer.rb
  app/serializers/json_ld/model_file_serializer.rb
  app/serializers/json_ld/model_serializer.rb
  spec/requests/api/json_ld/model_files_spec.rb
  spec/requests/api/json_ld/models_spec.rb
Labels: feature

#3815 Add icons to "open in slicer" menu options
  app/assets/stylesheets/src/model_files.scss
  app/controllers/application_controller.rb
  app/helpers/model_files_helper.rb
Labels: improvement

#3824 API improvements, linking resources together and improving JSON-LD
  app/api/v0/openapi.json
  app/serializers/json_ld/application_serializer.rb
  app/serializers/json_ld/collection_list_serializer.rb
  app/serializers/json_ld/collection_serializer.rb
  app/serializers/json_ld/creator_list_serializer.rb
  app/serializers/json_ld/creator_serializer.rb
  app/serializers/json_ld/model_file_serializer.rb
  app/serializers/json_ld/model_list_serializer.rb
  app/serializers/json_ld/model_serializer.rb
  spec/requests/api/json_ld/collections_spec.rb
  spec/requests/api/json_ld/creators_spec.rb
  spec/requests/api/json_ld/model_files_spec.rb
  spec/requests/api/json_ld/models_spec.rb
  spec/serializers/json_ld/collection_list_serializer_spec.rb
  spec/serializers/json_ld/creator_list_serializer_spec.rb
  spec/serializers/json_ld/model_list_serializer_spec.rb
  spec/swagger_helper.rb
Labels: feature

#3828 Ignore datapackage.json when generating filesystem change lists
  app/jobs/scan/detect_filesystem_changes_job.rb
Labels: bug

#3827 Fix extra slash on rpg-awesome path
  app/assets/stylesheets/application.scss
Labels: bug

#3837 Add custom validator for checking uniqueness across different tables
  Gemfile
  Gemfile.lock
  app/validators/multimodel_uniqueness_validator.rb
  spec/support/with_model.rb
  spec/validators/multimodel_uniqueness_validator_spec.rb
Labels: improvement

#3838 Ignore self in multimodel uniqueness check
  app/validators/multimodel_uniqueness_validator.rb
  spec/validators/multimodel_uniqueness_validator_spec.rb
Labels: bug

#3839 User fediverse handles now use username field
  app/models/application_record.rb
  app/models/collection.rb
  app/models/creator.rb
  app/models/model.rb
  app/models/user.rb
  app/validators/multimodel_uniqueness_validator.rb
  app/views/devise/registrations/edit.html.erb
Labels: improvement

#3844 Add editing for creator slugs (aka fedi usernames)
  app/controllers/creators_controller.rb
  app/models/concerns/sluggable.rb
  app/views/creators/_form.html.erb
  spec/requests/creators_spec.rb
Labels: feature

#3846 Add setting for default library, used when uploading
  app/controllers/libraries_controller.rb
  app/models/library.rb
  app/models/site_settings.rb
  app/views/libraries/_form.html.erb
  app/views/libraries/index.html.erb
  app/views/models/new.html.erb
  config/locales/en.yml
  config/locales/libraries/en.yml
Labels: feature

#3847 Improve wording for Creator slug/handle/username edit box
  app/views/creators/_form.html.erb
  config/locales/creators/en.yml
  config/locales/en.yml
Labels: improvement

#3852 Hide "unassigned" creator/collection if empty
  app/controllers/collections_controller.rb
  app/controllers/creators_controller.rb
  app/views/collections/_unassigned.html.erb
  app/views/collections/index.html.erb
  app/views/creators/_unassigned.html.erb
  app/views/creators/index.html.erb
Labels: feature

#3853 Send email to moderators when new accounts are created and need approval
  app/controllers/users/registrations_controller.rb
  app/mailers/moderator_mailer.rb
  app/views/moderator_mailer/new_approval.text.erb
  app/views/moderator_mailer/new_report.text.erb
  app/views/settings/reports/index.html.erb
  config/locales/en.yml
  spec/factories/report.rb
  spec/mailers/moderator_mailer_spec.rb
Labels: feature

#3854 Remove punctuation that breaks links in mailers
  config/locales/en.yml
Labels: bug

#3859 Fix signup validation failure bug
  app/controllers/users/registrations_controller.rb
Labels: bug

#3860 Require moderator approval for signups by default
  app/models/site_settings.rb
  spec/requests/users/registrations_spec.rb
Labels: feature, breaking change

#3862 Send notifications to moderators when a new report is received
  Gemfile
  Gemfile.lock
  app/services/report_handler.rb
  config/initializers/federails.rb
Labels: feature

#3863 Enable cs locale (Czech) on translation.io
  config/initializers/translation.rb
Labels: improvement

#3864 Update Federails as far as we can currently go pending fixes to local?
  Gemfile
  Gemfile.lock
Labels: dependencies

#3865 Change "enable signup" environment setting into a settings page option
  Gemfile
  Gemfile.lock
  app/controllers/settings_controller.rb
  app/models/site_settings.rb
  app/views/settings/multiuser.html.erb
  config/application.rb
  config/initializers/federails.rb
  config/locales/settings/en.yml
  env.example
Labels: feature

#3867 Move site name, icon, and tagline into site settings appearance page
  app/controllers/application_controller.rb
  app/controllers/settings_controller.rb
  app/helpers/application_helper.rb
  app/models/site_settings.rb
  app/views/settings/appearance.html.erb
  config/locales/settings/en.yml
Labels: feature

#3868 Add server rules to site settings, with markdown support and automatically shown at signup
  app/controllers/settings_controller.rb
  app/helpers/application_helper.rb
  app/models/site_settings.rb
  app/views/devise/registrations/new.html.erb
  app/views/settings/appearance.html.erb
  config/locales/devise/en.yml
  config/locales/settings/en.yml
Labels: feature

#3871 Add customisable "about" page for specific instance
  app/controllers/home_controller.rb
  app/controllers/settings_controller.rb
  app/models/site_settings.rb
  app/views/home/about.html.erb
  app/views/settings/appearance.html.erb
  config/locales/settings/en.yml
  config/routes.rb
Labels: feature

#3874 Add setting for an instance-specific financial support link
  app/controllers/settings_controller.rb
  app/models/site_settings.rb
  app/views/application/_footer.html.erb
  app/views/settings/appearance.html.erb
  config/locales/en.yml
  config/locales/settings/en.yml
Labels: feature

#3879 Only show version in footer to administrators
  app/views/application/_footer.html.erb
Labels: improvement

#3880 Don't include "JSON files only" as a download option
  app/controllers/models_controller.rb
Labels: bug

#3881 Translation updates for DE, ES, & PL
  config/locales/creators/de.yml
  config/locales/creators/es.yml
  config/locales/creators/fr.yml
  config/locales/creators/nl.yml
  config/locales/creators/pl.yml
  config/locales/de.yml
  config/locales/devise/de.yml
  config/locales/devise/es.yml
  config/locales/devise/fr.yml
  config/locales/devise/nl.yml
  config/locales/devise/pl.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/libraries/de.yml
  config/locales/libraries/es.yml
  config/locales/libraries/fr.yml
  config/locales/libraries/nl.yml
  config/locales/libraries/pl.yml
  config/locales/model_files/de.yml
  config/locales/model_files/es.yml
  config/locales/model_files/fr.yml
  config/locales/model_files/nl.yml
  config/locales/model_files/pl.yml
  config/locales/models/de.yml
  config/locales/models/es.yml
  config/locales/models/fr.yml
  config/locales/models/nl.yml
  config/locales/models/pl.yml
  config/locales/nl.yml
  config/locales/pl.yml
  config/locales/problems/de.yml
  config/locales/settings/de.yml
  config/locales/settings/es.yml
  config/locales/settings/fr.yml
  config/locales/settings/nl.yml
  config/locales/settings/pl.yml
Labels: improvement, localisation

#3882 Czech translation
  Rakefile
  app/javascript/src/uploads.ts
  config/application.rb
  config/i18n-tasks.yml
  config/locales/collections/cs.yml
  config/locales/creators/cs.yml
  config/locales/cs.yml
  config/locales/devise/cs.yml
  config/locales/libraries/cs.yml
  config/locales/model_files/cs.yml
  config/locales/models/cs.yml
  config/locales/problems/cs.yml
  config/locales/settings/cs.yml
Labels: feature, localisation

#3887 Show follower counts for Models, Creators and Collections
  app/components/follow_button_component.rb
  app/models/site_settings.rb
  app/views/collections/show.html.erb
  app/views/creators/show.html.erb
  app/views/models/show.html.erb
  config/locales/en.yml
  config/locales/models/en.yml
Labels: feature, federation

#3889 Don't store incoming activities
  Gemfile
  Gemfile.lock
  app/services/activity_pub/actor_activity_handler.rb
Labels: bug, federation
